Table Time {
id int
HourTime time
DateTime date
}

Table Climate {
id int
temparature float
sunshine float
}

Table Location {
id int
city varchar
Department varchar
}

Ref : Location.id > Climate.id
Ref : Location.id > Time.id
